kind: Cluster
metadata:
  name: eks-gitops-cluster2
  project: vijaspractice
spec:
  blueprint: default
  cloudprovider: aws-cloud-credential
  clusterConfig: null
  cniprovider: aws-cni
  proxyconfig: {}
  type: eks
---
apiVersion: rafay.io/v1alpha5
availabilityZones:
- us-west-2a
- us-west-2b
kind: ClusterConfig
metadata:
  name: eks-gitops-cluster2
  region: us-west-2
  version: "1.20"
managedNodeGroups:
- amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2a
  - us-west-2b
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
  instanceType: t3.xlarge
  maxSize: 1
  minSize: 1
  name: managed-ng1
  version: "1.20"
  privateNetworking: true
  volumeSize: 80
  volumeType: gp3
